services:
  soft-serve:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.soft-serve
      args:
        GO_IMAGE: ${GO_IMAGE}
        DEBIAN_IMAGE: ${DEBIAN_IMAGE}
        SOFT_SERVE_VERSION: ${SOFT_SERVE_VERSION}
    container_name: soft-serve
    environment:
      SOFT_SERVE_DATA_PATH: ${SOFT_SERVE_DATA_PATH}
      SOFT_SERVE_INITIAL_ADMIN_KEYS: ${SOFT_SERVE_INITIAL_ADMIN_KEYS}
      CI: ${CI}
    volumes:
      - ./data/soft-serve:${SOFT_SERVE_DATA_PATH}
    ports:
      - ${SOFT_SERVE_SSH_PORT}:${SOFT_SERVE_SSH_PORT}
      - ${SOFT_SERVE_HTTP_PORT}:${SOFT_SERVE_HTTP_PORT}
      - ${SOFT_SERVE_STATS_PORT}:${SOFT_SERVE_STATS_PORT}
      - ${SOFT_SERVE_GIT_PORT}:${SOFT_SERVE_GIT_PORT}
    expose:
      - "${SOFT_SERVE_SSH_PORT}"
    networks:
      - soft-serve-net
    restart: unless-stopped

  tor:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.tor
      args:
        DEBIAN_IMAGE: ${DEBIAN_IMAGE}
    environment:
      ONION_PUBLIC_PORT: ${ONION_PUBLIC_PORT}
      ONION_TARGET_PORT: ${ONION_TARGET_PORT}
    volumes:
      - ./data/tor:/var/lib/tor
    healthcheck:
      test: ["CMD", "tor", "--verify-config", "-f", "/etc/tor/torrc"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - soft-serve-net
    depends_on:
      - soft-serve

networks:
  soft-serve-net:
    driver: bridge
