services:
  tor-client:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.tor-client
      args:
        DEBIAN_IMAGE: ${DEBIAN_IMAGE}
    ports:
      - ${TOR_CLIENT_SOCKS_PORT}:9050
    expose:
      - "9050"
    networks:
      - soft-serve-net
