ARG ALPINE_IMAGE=alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40
FROM ${ALPINE_IMAGE}

RUN apk add --no-cache bash ca-certificates coreutils gettext-envsubst tini tor && \
    addgroup -g 10002 -S hidden-tor && \
    adduser -u 10002 -S -D -H -h /var/lib/tor -s /sbin/nologin -G hidden-tor hidden-tor && \
    install -d -o 10002 -g 10002 -m 0700 /var/lib/tor /run/hidden-git

COPY ./soft-serve-hidden-service.torrc.template /etc/tor/torrc.template
COPY --chmod=0755 scripts/tor-entrypoint.sh /usr/local/bin/hidden-git-tor-entrypoint
COPY --chmod=0755 scripts/tor-healthcheck.sh /usr/local/bin/hidden-git-tor-healthcheck
VOLUME ["/var/lib/tor"]
USER 10002:10002

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/hidden-git-tor-entrypoint"]
